### ISSUE TITLE
How to train on VISDA-C dataset

### ISSUE THREAD

**Issue by ShiyeLi** [tim-learn/ATDOC#2]
I simply use the demo of 【'**ATDOC-NA**' combined with '**CDAN+E**'】,change the dataloader with mine and set epochs=10,

python demo_uda.py --pl atdoc_na --tar_par 0.2 --dset VISDA-C --max_epoch 10 --s 0 --t 1 --gpu_id 1 --method CDANE --output logs/uda/run1/

but result only achieve 69.18%.
Can you relese hyper-parameters of training on VISDA-C dataset?
Thanks!

**Comment by tim-learn** [comment]
> I simply use the demo of 【'**ATDOC-NA**' combined with '**CDAN+E**'】,change the dataloader with mine and set epochs=10,
> 
> python demo_uda.py --pl atdoc_na --tar_par 0.2 --dset VISDA-C --max_epoch 10 --s 0 --t 1 --gpu_id 1 --method CDANE --output logs/uda/run1/
> 
> but result only achieve 69.18%.
> Can you relese hyper-parameters of training on VISDA-C dataset?
> Thanks!

You can try to adjust the hyper-parameter max_epoch to 1.
