### ISSUE TITLE
the form of idx

### ISSUE THREAD

**Issue by FRESHMAN11392** [tim-learn/ATDOC#5]
Hi,thanks for sharing your code! I have a question  in demo_uda , line 169. dis[di, idx[di]] = torch.max(dis)   What is the form of idx, I can't get it through iter.next() in the dataset I built myself (not the image public dataset)，thank you

**Comment by tim-learn** [comment]
> Hi,thanks for sharing your code! I have a question in demo_uda , line 169. dis[di, idx[di]] = torch.max(dis) What is the form of idx, I can't get it through iter.next() in the dataset I built myself (not the image public dataset)，thank you

Sorry, I just find this question today. idx is the index of images in the dataset. you can check Line 246 in the utils.py for more details.

**Comment by FRESHMAN11392** [comment]
I've solved the problem, thank you very much for your great work

**Comment by FRESHMAN11392** [comment]
Thank u
